exfat/super: Use `exfat_err()` instead of deprecated `exfat_msg()`
- This fixes the below error:

../fs/exfat/super.c: In function 'exfat_parse_options':
../fs/exfat/super.c:385:33: error: implicit declaration of function 'exfat_msg'; did you mean 'exfat_err'? [-Werror=implicit-function-declaration]
  385 |                                 exfat_msg(sb, KERN_ERR,
      |                                 ^~~~~~~~~
      |                                 exfat_err
cc1: some warnings being treated as errors

Signed-off-by: Cyber Knight <cyberknight755@gmail.com>
Signed-off-by: KiGamji <maloyh44@gmail.com>
Signed-off-by: MrErenK <akbaseren4751@gmail.com>